export const downloadReport = (type, result) => {
    const reportData = {
        project: "CyberShield EDU",
        timestamp: new Date().toLocaleString(),
        scan_type: type,
        prediction: result.prediction,
        confidence: result.confidence || result.scam_score,
        reasoning: result.reasoning,
        metadata: result.metadata,
        disclaimer: "This report is generated by AI-powered heuristics. Always verify safety with official authorities."
    };

    const blob = new Blob([JSON.stringify(reportData, null, 2)], { type: 'application/json' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `CyberShield_Report_${type}_${Date.now()}.json`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
};
